#pragma once

#define PMW3320_CS_PIN A7
#define PMW3320_SDIO_PIN A6
#define PMW3320_SCLK_PIN B1
#define POINTING_DEVICE_MOTION_PIN B0
#define POINTING_DEVICE_MOTION_PIN_ACTIVE_LOW

#define DEBUG_MATRIX_SCAN_RATE
//#define POINTING_DEVICE_TASK_THROTTLE_MS 1
#define POINTING_DEVICE_HIRES_SCROLL_ENABLE
#define WHEEL_EXTENDED_REPORT
#define MOUSE_EXTENDED_REPORT
