#pragma once

#define MAXTOUCH_BOOTLOADER_GESTURE
#define SPLIT_DIGITIZER_ENABLE
#define DIGITIZER_RIGHT
#define DIGITIZER_TASK_THROTTLE_MS 1
#define DIGITIZER_CONTACT_COUNT 5
#undef SPLIT_POINTING_ENABLE
#undef POINTING_DEVICE_RIGHT

#define AZOTEQ_IQS5XX_TPS43
