// Copyright 2022 Dasky (@daskygit)
// SPDX-License-Identifier: GPL-2.0-or-later
#pragma once

#define EE_HANDS

#define SELECT_SOFT_SERIAL_SPEED 0

#define CRC8_USE_TABLE
#define CRC8_OPTIMIZE_SPEED

#define OVERRIDE_DEBOUNCE 2

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED WS2812_DI_PIN
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U
