// Copyright 2022 Dasky (@daskygit)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define I2C1_SCL_PIN B8
#define I2C1_SDA_PIN B9
#define I2C1_CLOCK_SPEED 400000
#define I2C1_DUTY_CYCLE FAST_DUTY_CYCLE_2

#define WS2812_PWM_DRIVER PWMD2
#define WS2812_PWM_CHANNEL 3
#define WS2812_PWM_PAL_MODE 1
#define WS2812_DMA_STREAM STM32_DMA1_STREAM1
#define WS2812_DMA_CHANNEL 3
//#define WS2812_EXTERNAL_PULLUP

#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_RAINBOW_SWIRL
#define RGB_MATRIX_LED_COUNT 48
#define WS2812_DI_PIN B10

#define ENCODERS_PAD_A \
    { A8 }
#define ENCODERS_PAD_B \
    { A15 }

#define DEBUG_MATRIX_SCAN_RATE

// FRAM MB85RC16PNF-G-JNERE1
// #define EXTERNAL_EEPROM_I2C_BASE_ADDRESS 0b10100000
// #define EXTERNAL_EEPROM_I2C_ADDRESS(loc) (EXTERNAL_EEPROM_I2C_BASE_ADDRESS | ((((loc) >> 8) & 0x07) << 1))
// #define EXTERNAL_EEPROM_BYTE_COUNT 2048
// #define EXTERNAL_EEPROM_PAGE_SIZE 128 // Doesn't seem to have a limit for page writes?
// #define EXTERNAL_EEPROM_ADDRESS_SIZE 1
// #define EXTERNAL_EEPROM_WRITE_TIME 0
