#pragma once

#define ADNS9800_CS_PIN F7
#define POINTING_DEVICE_MOTION_PIN B6
#define ADNS9800_UPLOAD_SROM
#define DEBUG_MATRIX_SCAN_RATE
#define POINTING_DEVICE_DEBUG
#define POINTING_DEVICE_ROTATION_270
#define POINTING_DEVICE_INVERT_Y
#define ADNS9800_CPI 6400
#ifdef CONVERT_TO_RP2040_CE
#    define SPI_DRIVER SPID0
#    define SPI_SCK_PIN B1
#    define SPI_MISO_PIN B3
#    define SPI_MOSI_PIN B2
#endif
#define ADNS9800_SPI_DIVISOR 128
