// Copyright 2024 Dasky (@Dasky)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define PS2_RDY GP6
#define PS2_DATA GP28
#define PS2_CLK GP29
#define PS2_PIO_USE_PIO1

#define TPS_RDY GP4
#define TPS_SDA GP2
#define TPS_SCL GP3

#define CIRQUE_SS GP21
#define CIRQUE_MOSI GP23
#define CIRQUE_MISO GP20
#define CIRQUE_CLK GP22
#define CIRQUE_RDY GP26
#define CIRQUE_PINNACLE_SPI_CS_PIN CIRQUE_SS

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 200U
#define SERIAL_USART_FULL_DUPLEX
// #define SERIAL_USART_TX_PIN GP0
#define SERIAL_USART_RX_PIN GP1
#define SERIAL_USART_PIN_SWAP
#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP2
#define I2C1_SCL_PIN GP3

#define AZOTEQ_IQS5XX_TPS43
#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_COMBINED

#define POINTING_DEVICE_COUNT 4

#define USB_VBUS_PIN GP19
#define MASTER_RIGHT
#define SPLIT_HAND_PIN GP11
#define SPLIT_HAND_PIN_LOW_IS_LEFT

#define SPI_DRIVER SPID0
#define SPI_SCK_PIN GP22
#define SPI_MISO_PIN GP20
#define SPI_MOSI_PIN GP23

#define POINTING_DEVICE_DEBUG
#define SERIAL_DEBUG
#define DEBUG_MATRIX_SCAN_RATE

#define SERIAL_USART_SPEED 2000000
#define CRC8_USE_TABLE
#define CRC8_OPTIMIZE_SPEED

#define I2C1_CLOCK_SPEED 1000000
